---
output: github_document
always_allow_html: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# goslingr

<!-- badges: start -->
<!-- badges: end -->

The goal of goslingr is to ...

## Installation

You can install the development version of goslingr from [GitHub](https://github.com/) with:

``` r
# install.packages('remotes')
remotes::install_github('ccb-hms/goslingr')
```

## Example

Generate a gosling bar chart from the [example spec](https://gosling.js.org/?example=doc_bar):

```{r barchart}
library(goslingr)

# import bar chart spec file
bar_chart_spec_fpath <- system.file('extdata', 'bar_chart_spec.json', package = 'goslingr')
bar_chart_spec <- jsonlite::read_json(bar_chart_spec_fpath)

# generate gosling bar plot from spec
goslingr(bar_chart_spec)
```

Generate a gosling lollipop plot from the [example spec](https://gosling.js.org/?example=MARK_DISPLACEMENT):

```{r lollipop}
# import lollipops plot spec file
lollipop_spec_fpath <- system.file('extdata', 'lollipop_plots_spec.json', package = 'goslingr')
lollipop_spec <- jsonlite::read_json(lollipop_spec_fpath)

goslingr(lollipop_spec)
```
